title: Anuja Kishore Merwade
logo: /Anuja_Merwade_headshot.png
description: Highly motivated software professional with 3+ years of experience in data engineering, modeling, analytics, backend development and cloud. Demonstrated expertise in efficient problem-solving, building robust data pipelines, cloud migration and APIs.
show_downloads: true
theme: jekyll-theme-minimal
